######################################################################
# Automatically generated by qmake (3.0) ?r. cze 27 11:15:15 2018
######################################################################

TEMPLATE = app
CONFIG += c++11
TARGET = parse
INCLUDEPATH += .
include (../../common.pri)

# Input
SOURCES += main.cpp
